DROP TABLE COM_HISTORIAL_COMPRA CASCADE CONSTRAINTS;
DROP TABLE COM_HISTORIAL_PAGO CASCADE CONSTRAINTS;
DROP TABLE COM_NOTIFICACION_COMPRA CASCADE CONSTRAINTS;
DROP TABLE COM_ORDEN_COMPRA CASCADE CONSTRAINTS;
DROP TABLE COM_PRODUCTO CASCADE CONSTRAINTS;
DROP TABLE COM_PROVEEDOR CASCADE CONSTRAINTS;