DROP TABLE VEN_CALIFICACIONES_CLIENTES CASCADE CONSTRAINTS;
DROP TABLE VEN_CLIENTES CASCADE CONSTRAINTS;
DROP TABLE VEN_DESCUENTOS CASCADE CONSTRAINTS;
DROP TABLE VEN_METODO_PAGO CASCADE CONSTRAINTS;
DROP TABLE VEN_PEDIDOS CASCADE CONSTRAINTS;
